version: "3.9"

services:
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data_flask:/var/lib/postgresql/data

  api:
    image: devoind/app:latest
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: db
      FLASK_ENV: production
      FLASK_APP: run:app
    ports:
      - "8080:5000"
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "python3 -m flask run -h 0.0.0.0 -p 5000"
    healthcheck:
      test: curl -sS http://127.0.0.1:5000/ping/ || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  pg_data_flask:

